# Generated by Django 4.1.2 on 2022-11-05 05:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longLink', models.CharField(max_length=1000)),
                ('shortCode', models.CharField(max_length=30)),
                ('creationDate', models.DateField(default=datetime.date.today)),
                ('clicks', models.IntegerField(default=0)),
                ('status', models.CharField(default='Pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IP_Adresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(default='192.168.0.1')),
                ('shortCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.url')),
            ],
        ),
    ]
