# Generated by Django 4.1.2 on 2022-11-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_remove_url_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
