# Generated by Django 4.1.2 on 2022-11-21 03:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_url_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_adresses',
            name='visitedDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='url',
            name='verification',
            field=models.BooleanField(default=False),
        ),
    ]
